#! /bin/sh

touch NEWS ChangeLog 

gettextize -f --no-changelog \
&& sed 's/po\/Makefile.in po\/Makefile.in/po\/Makefile.in/' < configure.in > configure.tmp \
&& mv configure.tmp configure.in \
&& sed 's/config.rpath *config.rpath/config.rpath/g' < Makefile.am > Makefile.amtmp \
&& mv Makefile.amtmp Makefile.am \
&& aclocal --verbose \
&& autoheader -v  \
&& automake -v --gnu --add-missing -c \
&& autoconf -v

touch m4/ChangeLog
touch po/ChangeLog
