#ifndef __id_updaterMainFrame__
#define __id_updaterMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "id_updater_gen.h"
#include "wx/download.h"
#include <wx/xml/xml.h>
#include "InstallChecker.h"

/** Implementing MainFrame */
class id_updaterMainFrame : public MainFrame
{
	wxDownloadThread *m_dThread;
	wxString m_baseURI;
	wxString m_basePath;
	bool m_downloadingXml;
	wxXmlDocument m_xmlDoc;
	int m_downloadIndex;
	int m_installIndex;
	wxGauge * m_curGauge;
	wxStaticText* m_curDownloadText;
	InstallChecker installer;
public:
	/** Constructor */
	id_updaterMainFrame( wxWindow* parent, wxString baseUrl );
	virtual ~id_updaterMainFrame();
	virtual void OnClick( wxCommandEvent& event );
	virtual void OnCancel( wxCommandEvent& event );
	virtual void id_updaterMainFrame::OnClose( wxCloseEvent& event );
	virtual void downloadClick( wxCommandEvent& event );
	virtual void OnUpdateUI( wxUpdateUIEvent& event );
	virtual void OnClickAdd( wxCommandEvent& event );
	virtual void OnCheckUpdates( wxCommandEvent& event );

	void OnDownloadComplete(wxCommandEvent &);
	void addProductPanel(wxXmlNode *node);
	void clearProducts();
	void loadProducts();
	void startNextDownload();
	void startNextInstall();
};

#endif // __id_updaterMainFrame__
