#pragma once

template <class T>
class CProxy_ISmartCardSignerEvents : public IConnectionPointImpl<T, &__uuidof( _ISmartCardSignerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
